name: Run Vercel Job

on:
  schedule:
    - cron: "7 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Vercel Job
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
        run: |
          curl -X GET \
            -H "Authorization: Bearer $CRON_SECRET" \
            https://leaving-match.vercel.app/api/test
